config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  root to: 'home#top'

  resources :users, only: %i[show] do
    member do
      get 'mypage', param: :uid
      get 'myprofile'
      get 'myfavorite'
      get 'mypost'
    end
  end
  resources :divesites, only: %i[index show] do
    collection do
      get 'select_map'
    end
  end
  resources :conditions, only: %i[index show new create destroy]
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[] do
    collection do
      post 'follow', to: 'relationships#create', as: :follow
    end
    member do
      delete 'unfollow', to: 'relationships#destroy', as: :unfollow
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  has_many :conditions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  validates :name, presence: true, length: { maximum: 30 }

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[google]

  def to_param
    uid
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    user ||= User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid: auth.uid,
                      password: Devise.friendly_token[0, 20])
    user.save
    user
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64
      user.uid = SecureRandom.uuid.tr('-', '')
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'guest.admin@example.com') do |user|
      user.name = 'ゲスト(管理者)'
      user.password = SecureRandom.urlsafe_base64
      user.uid = SecureRandom.uuid.tr('-', '')
      user.admin = true
    end
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update(params, *options)
    clean_up_passwords
    result
  end

  def follow(user)
    follower.create!(followed_id: user.id)
  end

  def unfollow(user)
    follower.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    follower.find_by(followed_id: user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    def google
      @user = User.find_for_google(request.env['omniauth.auth'])
      if @user.persisted?
        bypass_sign_in(@user)
        redirect_to mypage_user_url(@user), event: :authentication
        set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
      else
        session['devise.google_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_account_update_params, only: [:update]

    def build_resource(hash = {})
      hash[:uid] = User.create_unique_string
      super
    end

    private

    def after_sign_up_path_for(resource)
      mypage_user_url(resource)
    end

    def after_update_path_for(resource)
      mypage_user_url(resource)
    end

    def update_resource(resource, params)
      resource.update_without_current_password(params)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    def guest_sign_in
      user = User.guest
      sign_in user
      redirect_to mypage_user_url(user.uid)
      flash[:notice] = 'ゲスト(ユーザー)としてログインしました！'
    end

    def guest_admin_sign_in
      admin_user = User.guest_admin
      sign_in admin_user
      redirect_to mypage_user_url(admin_user.id)
      flash[:notice] = 'ゲスト(管理者)としてログインしました！'
    end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end

    def after_sign_in_path_for(resource)
      mypage_user_url(resource)
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include UsersHelper
  before_action :authenticate_user!
  before_action :set_user, only: %i[show]

  def show
    if @user.nil?
      redirect_to root_url
      flash[:alert] = 'お探しのページは見つかりません'
    else
      @conditions = @user.conditions.includes(:divesite).order(created_at: :DESC)
      @conditions = @conditions.page(params[:page]).per(10)
    end
  end

  def mypage
    if current_user.uid == params[:id]
      @favorites = current_user.favorites.includes(:divesite).order(created_at: :DESC)
      @followed = current_user.follower.includes(:followed).order(created_at: :DESC)
    else
      redirect_to root_url
      flash[:alert] = 'お探しのページは見つかりません'
    end
  end

  def myprofile
    respond_to do |format|
      format.js { render :myprofile }
      format.html { redirect_to mypage_user_path(current_user.uid) }
    end
  end

  def myfavorite
    @favorites = current_user.favorites.includes(:divesite).order(created_at: :DESC)
    @followed = current_user.follower.includes(:followed).order(created_at: :DESC)
    respond_to do |format|
      format.js { render :myfavorite }
      format.html { redirect_to mypage_user_path(current_user.uid) }
    end
  end

  def mypost
    @conditions = current_user.conditions.order(created_at: :DESC)
    @conditions = @conditions.page(params[:page]).per(10)
    respond_to do |format|
      format.js { render :mypost }
      format.html { redirect_to mypage_user_path(current_user.uid) }
    end
  end

  private

  def user_params
    params.reguire(:user).permit(:name, :email, :avatar, :avatar_cache)
  end

  def set_user
    user = User.all.pluck(:uid)
    @user = User.find_by(uid: params[:id]) if params[:id].in?(user)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def set_avatar_helper
    if current_user.avatar?
      current_user.avatar.url
    else
      '/images/default-avatar.png'
    end
  end

  def complete_profile_helper
    'プロフィールを完成するには『プロフィール編集』' if current_user.avatar.blank? || current_user.shop.blank?
  end
end

app/views/users/_myfavorite.html.erb
<div class="myfavorite">
  <h4 class="pt-2 pb-4 my-favorite"><i class="fas fa-laugh-squint"></i> お気に入りダイブサイト</h4>
  <div class="">
    <h5 class="pl-4">
      <% favorites.each do |favorite| %>
      <div class="pb-3">
        <%= link_to divesite_path(favorite.divesite.id) do %>
          <i class="fas fa-angle-double-right" data-toggle="tooltip" data-placement="right" title="詳細ページへ"><%= " #{favorite.divesite.name}" %></i>
        <% end %>
      </div>
      <% end %>
    </h5>
  </div>
  <h4 class="pt-5 pb-4 my-favorite"><%= image_tag("/images/users/like.svg", class: "follow") %> フォロー中のユーザー</h4>
  <div class="">
    <h5 class="pl-4">
      <% followed.each do |follow| %>
      <div class="pb-3">
        <%= link_to user_path(follow.followed.uid) do %>
          <i class="fas fa-angle-double-right" data-toggle="tooltip" data-placement="right" title="詳細ページへ"><%= " #{follow.followed.name}" %></i>
        <% end %>
      </div>
      <% end %>
    </h5>
  </div>
</div>

app/views/users/_mypost.html.erb
<div class="mypost-wrap">
  <div class="mypost-title  d-flex">
    <span><h4 class="mt-1 pt-1 pb-4">自分の投稿一覧</h4></span>
    <%= link_to new_condition_path, class: 'transition-btn ml-4' do %>
      <i class="fas fa-plus"> 海況投稿</i>
    <% end %>
  </div>
  <div class="">
    <p>
      <% conditions.each do |condition| %>
      <div class="pb-3">
        <%= link_to condition_path(condition.id) do %>
          <i class="fas fa-angle-double-right" data-toggle="tooltip" data-placement="right" title="投稿詳細へ"><%= " #{condition.created_at.strftime("%-m月%e日")} / #{condition.divesite.zone} / #{condition.divesite.name}" %></i>
        <% end %>
      </div>
      <% end %>
    </p>
    <div class="mb-2 d-flex justify-content-center">
      <%= paginate conditions, remote: true %>
    </div>
  </div>
</div>

app/views/users/_myprofile.html.erb
<div class="myprofile">
  <p id="empty-caution"><%= complete_profile_helper %></p>
  <h4 class="pt-2 pb-2 my-profile">プロフィール</h4>
  <table>
    <tr>
      <th>ユーザ名</th>
      <td><p><%= current_user.name %></p></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><p><%= current_user.email %></p></td>
    </tr>
    <tr>
      <th>所属店</th>
      <% if current_user.shop.present? %>
        <td><p><%= current_user.shop %></p></td>
      <% else %>
        <td><p>未設定</p></td>
      <% end %>
    </tr>
  </table>
  <div class="myprofile-links pt-3 d-flex justify-content-around">
    <div class="transition-btn"><%= link_to 'プロフィール編集', edit_user_registration_path, class: "" %></div>
    <div class="">
      <%= link_to user_registration_path, method: :delete, data: { confirm: 'アカウントを削除しますか？' }, class: "unobtrusive" do %>
        <%= "アカウント削除" %><i class="fas fa-angle-right"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/users/myfavorite.js.erb
$("#mypage-content").html("<%= j(render 'myfavorite', { favorites: @favorites, followed: @followed, totalling: @totalling }) %>");

app/views/users/mypage.html.erb
<div class="container-fluid mypage-top-wrap">
  <div class="row mypage-top">
      <%= image_tag(set_avatar_helper, class: 'avatar-image-top') %>
      <div class="mask-gradation"></div>
    <p class="user-name-wrap"><span class="user-name"><%= "#{current_user.name} " %></span><span class="user-follower-count">フォロワー <%= current_user.follower_user.count %></span></p>
    <aside class="col-sm-4 col-md-4 col-lg-3 floating-board">
      <a class="close-btn" href="#">
        <i class="fas fa-window-close"></i>
      </a>
      <div>
        <%= image_tag(set_avatar_helper, class: 'avatar-image') %>
      </div>
      <nav class="side-menu">
        <ul>
          <li class="mymenu currently-selected"><%= link_to 'お気に入り / フォロー中', myfavorite_user_path(current_user.uid), class: "mymenu-link", remote: true %></li>
          <li class="mymenu"><%= link_to '自分の投稿一覧', mypost_user_path(current_user.id), class: "mymenu-link", remote: true %></li>
          <li class="mymenu"><%= link_to 'プロフィール', myprofile_user_path(current_user.uid), class: "mymenu-link", remote: true %></li>
        </ul>
      </nav>
    </aside>
  </div>
</div>
<div class="container-fluid wrapper">
  <div class="row">
    <div class="empty-element"></div>
    <article class="">
      <a class="sidemenu-btn" href="#">
        <i class="fas fa-bars"> マイページメニュー</i>
      </a>
      <div id="mypage-content">
        <%= render 'myfavorite', { favorites: @favorites, followed: @followed} %>
      </div>
    </article>
  </div>
</div>

app/views/users/mypost.js.erb
$("#mypage-content").html("<%= j(render 'mypost', conditions: @conditions ) %>");

app/views/users/myprofile.js.erb
$("#mypage-content").html("<%= j(render 'myprofile') %>");

app/views/users/show.html.erb
<div class="container-fluid user-show-top-wrap">
  <div class="row">
    <div class="col-sm-1 col-lg-2"></div>
    <div class="col-sm-10 col-md-12 col-lg-8 row user-show-top">
      <div class="col-sm-6 col-md-6 col-lg-6 user-show-left">
        <% if @user.avatar? %>
          <%= image_tag(@user.avatar.url, class: "avatar-image-top") %>
        <% else %>
          <%= image_tag('/images/default-avatar.png', class: "avatar-image-top") %>
        <% end %>
      </div>
      <div class="col-sm-6 col-md-6 col-lg-6 user-show-right">
        <h2 class="pb-3"><span><%= "#{@user.name} " %></span></h2>
        <div class="user-info">
          <div class="">
          <% if @user.shop.present? %>
            <h5><small>所属店: </small><%= @user.shop %></h5>
          <% else %>
            <h5><small>所属店: </small><span>未設定</span></h5>
          <% end %>
          </div>
          <div class="follow-part">
            <% unless current_user.id == @user.id %>
              <span id="follow-part">
                <%= render 'relationships/follow', user: @user %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-1 col-lg-2"></div>
  </div>
  <div class="row">
    <div class="col-sm-1 col-lg-2"></div>
    <div class="col-sm-10 col-md-12 col-lg-8 user-show-bottom">
      <div class="user-show-post">
        <div class="">
          <p class="pt-4 pb-4 headding past-posts-title"><span><%= "#{@user.name}" %>さんの</span><span>投稿一覧</span></p>
          <div class="mt-5">
            <% if @conditions.present? %>
              <% @conditions.each do |condition| %>
              <div class="pb-3">
                <p class="past-posts">
                  <%= link_to condition_path(condition.id) do %>
                    <i class="fas fa-angle-double-right" data-toggle="tooltip" data-placement="right" title="投稿詳細へ"><%= " #{condition.created_at.strftime("%-m月%e日")} / #{condition.divesite.zone} / #{condition.divesite.name}" %></i>
                  <% end %>
                </p>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="mb-2 d-flex justify-content-center">
        <%= paginate(@conditions) %>
      </div>
      <div class="pt-2 unobtrusive">
        <%= link_to conditions_path, class: "unobtrusive" do %>
          <%= "海況投稿一覧へ戻る" %><i class="fas fa-angle-right"></i>
        <% end %>
      </div>
    </div>
    <div class="col-sm-1 col-lg-2"></div>
  </div>
</div>