config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  root to: 'home#top'

  resources :users, only: %i[show] do
    member do
      get 'mypage', param: :uid
      get 'myprofile'
      get 'myfavorite'
      get 'mypost'
    end
  end
  resources :divesites, only: %i[index show] do
    collection do
      get 'select_map'
    end
  end
  resources :conditions, only: %i[index show new create destroy]
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[] do
    collection do
      post 'follow', to: 'relationships#create', as: :follow
    end
    member do
      delete 'unfollow', to: 'relationships#destroy', as: :unfollow
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def top; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/top.html.erb
<div class="container-fluid">
  <div class="background">
    <div class="top-front">
      <div class="top-logo">
        <div class="top-logo-inner">
          <%= image_tag("/images/PRODIVE_lightblue.png", height: 45) %><br>
          <p class="top-title-01">プロの資格を持つダイバーの為の<br>海況共有アプリ</p>
          <p class="top-title-02">今日どこに潜りに行く？</p>
        </div>
      </div>
      <div class="scroll-invitation"><span>Scroll</span></div>
      <%= image_tag '/images/diver.png', class: "diver" %>
    </div>
    <div class="row">
      <div class="col-sm-1 col-md-1 col-lg-2"></div>
      <div class="col-sm-10 col-md-10 col-lg-8">
        <div class="translucent-box left">
          <p class="title"><small><i class="fas fa-lightbulb"></i></small> PRODIVEとは</p>
          <p class="text">プロダイバーの朝の忙しさを</p>
          <p class="text mb-3">少しでも解消したい…</p>
          <p class="text">潜る前のお客様との時間を</p>
          <p class="text mb-3">有意義に使いたい…</p>
          <p class="text">そういった思いからできました</p>
        </div>
        <div class="translucent-box right">
          <p class="title"><small><i class="fas fa-thumbs-up"></i></small> PRODIVEのメリット</p>
          <p class="text">初心者向けの</p>
          <p class="text mb-3">穏やかな海況のところは？</p>
          <p class="text">今日とりあえずOPENしている</p>
          <p class="text mb-3">ダイビングサイトが知りたい！</p>
          <p class="text">そんなプロダイバーに</p>
          <p class="text mb-3">判断の目安になる情報を一覧で表示</p>
          <p class="text">また、ダイブサイト側の方は</p>
          <p class="text">海況情報や生物情報など</p>
          <p class="text mb-3">アピールができる場となります</p>
        </div>
        <div class="translucent-box left">
          <p class="title"><small>
            <%= link_to divesites_path do %>
              <i class="fas fa-map-marked-alt"> 海況MAPについて</i>
            <% end %></small>
          </p>
          <p class="text">サイドメニューで</p>
          <p class="text mb-3">確認したいエリアを選択できます</p>
          <p class="text">表示されたMAPのPIN画像は</p>
          <p class="text mb-3">当日の情報が反映されています</p>
          <p class="text">OPEN / 潜水注意 / CLOSE が</p>
          <p class="text mb-3">一目ですぐに判断できます</p>
          <p class="text"><small>※ ログイン不要</small></p>
        </div>
        <div class="translucent-box right">
          <p class="title"><small>
          <% if user_signed_in? %>
            <%= link_to conditions_path do %>
              <i class="fas fa-water"> 本日の海況</i>
            <% end %></small>
          <% else %>
            <p class="title"><small><i class="fas fa-water"></i></small> 本日の海況</p>
          <% end %>
          </p>
          <p class="text">各ダイブサイトの</p>
          <p class="text mb-3">海況投稿を一覧で確認できます</p>
          <p class="text">どこのダイブサイトに</p>
          <p class="text mb-3">お客様をお連れするのが良いか</p>
          <p class="text">その判断に必要な情報として</p>
          <p class="text">透明度や水温、生物など</p>
          <p class="text">より詳しく見ることができます</p>
        </div>
        <div class="translucent-box left">
          <p class="title"><small>
          <% if user_signed_in? %>
            <%= link_to new_condition_path do %>
              <i class="fas fa-plus"> 海況投稿</i>
            <% end %></small>
          <% else %>
            <p class="title"><small><i class="fas fa-plus"></i></small> 海況投稿</p>
          <% end %>
          </p>
          <p class="text">各ダイブサイトを</p>
          <p class="text">管理しているサービスの方や</p>
          <p class="text">実際の海況を確認できる方が</p>
          <p class="text mb-3">当日の海況を投稿します</p>
          <p class="text">どこに潜りに行くか</p>
          <p class="text">決めかねているプロダイバーに</p>
          <p class="text mb-3">情報発信する場となります</p>
          <p class="text"><small>※ SNSへの投稿も流れでできます</small></p>
        </div>
        <div class="translucent-box right mb-4">
          <p class="title"><small>
          <% if user_signed_in? %>
            <%= link_to mypage_user_path(current_user.uid) do %>
              <i class="fas fa-portrait"> マイページ</i>
            <% end %></small>
          <% else %>
            <p class="title"><small><i class="fas fa-portrait"></i></small> マイページ</p>
          <% end %>
          </p>
          <p class="text">お気に入りのダイブサイト一覧</p>
          <p class="text">フォローしているユーザーの一覧</p>
          <p class="text">自分の海況投稿一覧など</p>
          <p class="text">全てを管理するところです</p>
          <br>
          <br>
          <br>
          <br>
          <br>
        </div>
        <div class="scrolldown-area">
          <ul class="timeline">
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
            <li>
              <div class="spacing"></div>
              <span class="border-line"></span>
            </li>
          </ul>
        </div>
        <% if user_signed_in? %>
          <div class="top-bottom">
            <div class="after-login">
              <p>海況MAPでお好きなダイビングサイトが</p>
              <p>今日OPENしてるかみてみましょう</p>
              <div class="d-flex justify-content-center">
                <%= link_to '海況MAPへ', divesites_path, class: 'm-3' %>
              </div>
              <p><small>現地サービスの方の海況投稿のご協力をお待ちしています</small></p>
            </div>
          </div>
        <% else %>
          <div class="top-bottom">
            <div class="links d-flex justify-content-center">
              <div class="transition-btn">
                <%= link_to 'ログイン', new_user_session_path %>
              </div>
              <div class="ml-3 transition-btn">
                <%= link_to 'アカウント登録', new_user_registration_path %>
              </div>
            </div>
            <div class="mt-4 d-flex justify-content-center">
              <%= link_to user_google_omniauth_authorize_path, class: 'm-4 oauth-google' do %>
                <i class="fas fa-angle-right"> Gmailでログイン</i>
              <% end %>
              <%= image_tag '/images/diver.png', class: "diver02" %>
            </div>
            <div class="d-flex justify-content-center">
              <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: 'mb-2 guest-login' %>
            </div>
            <div class="d-flex justify-content-center">
              <%= link_to 'ゲストログイン(管理者)', users_guest_admin_sign_in_path, method: :post, class: 'm-2 guest-login' %>
            </div>
          </div>
        <% end %>
        <p class="copywright"><small>© 2021 PRODIVE All rights reserved.</small></p>
      </div>
      <div class="col-sm-1 col-md-1 col-lg-2"></div>
    </div>
  </div>
</div>