config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  root to: 'home#top'

  resources :users, only: %i[show] do
    member do
      get 'mypage', param: :uid
      get 'myprofile'
      get 'myfavorite'
      get 'mypost'
    end
  end
  resources :divesites, only: %i[index show] do
    collection do
      get 'select_map'
    end
  end
  resources :conditions, only: %i[index show new create destroy]
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[] do
    collection do
      post 'follow', to: 'relationships#create', as: :follow
    end
    member do
      delete 'unfollow', to: 'relationships#destroy', as: :unfollow
    end
  end
end

app/models/divesite.rb
# frozen_string_literal: true

class Divesite < ApplicationRecord
  validates :area, :zone, :name, :latitude, :longitude, presence: true
  has_many :conditions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  require './app/commonclass/area'
  enum area: Area.options_for_enum

  require './app/commonclass/zone'
  enum zone: Zone.options_for_enum

  def added_to_favorites?(divesite)
    favorites.find_by(divesite_id: divesite.id)
  end
end

app/controllers/divesites_controller.rb
# frozen_string_literal: true

class DivesitesController < ApplicationController
  before_action :authenticate_user!, only: %i[show]

  def index
    @divesites = Divesite.all.order(id: :ASC)
    @areas = @divesites.pluck(:area).uniq

    gon.divesites = @divesites.map do |divesite|
      condition = divesite.conditions.where(created_at: Time.zone.now.all_day).last
      status = if condition.nil?
                 'noinfo'
               else
                 condition.status
               end
      { id: divesite.id,
        name: divesite.name,
        latitude: divesite.latitude,
        longitude: divesite.longitude,
        status: status }
    end
  end

  def show
    @divesite = Divesite.find(params[:id])
    @favorite = current_user.favorites.find_by(divesite_id: @divesite.id)
    @conditions = Condition.where(divesite_id: @divesite.id).includes(:user).order(created_at: :DESC)
    @conditions = @conditions.page(params[:page]).per(7)
  end

  def select_map
    respond_to do |format|
      if params[:zone]
        @divesites = Divesite.all
        @zones = @divesites.where(zone: params[:zone])
        format.js { render :select_zone }
      else
        format.html { redirect_to divesites_url, notice: '表示したいエリアを選択してください' }
      end
    end
  end
end

app/helpers/divesites_helper.rb
# frozen_string_literal: true

module DivesitesHelper
end

app/views/divesites/_select_zone.html.erb
<div class="change-map-contents">
  <div class="d-flex justify-content-around card-wrap">
    <% zones.each do |zone| %>
    <div class="item">
      <%= link_to divesite_path(zone) do %>
        <span>
          <%= image_tag '/images/divesites/airtank.png', class: "diving-icon" %>
          <%= zone.name %><i class="fas fa-angle-right"></i>
        </span>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/divesites/index.html.erb
<div class="container-fluid sea-condition-map">
  <div class="wrapper">
    <a class="select-menu-btn" href="#">
      <i class="fas fa-bars"> ダイブサイト選択メニュー</i>
    </a>
    <div class="row">
      <div class="col-sm-4 col-md-4 col-lg-3 floating-board">
        <a class="close-btn" href="#">
          <i class="fas fa-window-close"></i>
        </a>
        <nav class="select-map-range">
          <h5 class="heading01"><span>地図を</span><span>表示させたい</span><span>エリアを選択</span></h5>
          <% @areas.each do |area| %>
            <ul>
              <li>
                <i class="sidebar_icon before-click"></i>
                <h3 class="select-area"><%= area %></h3>
                <% @zones = @divesites.where(area: area) %>
                <% @zones.pluck(:zone).uniq.each do |zone| %>
                  <ul class="zone-list">
                    <li>
                      <%= link_to zone, select_map_divesites_path(zone: zone), data: {lat: "#{@zones.find_by(zone: zone).latitude}", lng: "#{@zones.find_by(zone: zone).longitude}"}, class: "zone", remote: true %>
                    </li>
                  </ul>
                <% end %>
              </li>
            </ul>
          <% end %>
        </nav>
      </div>
      <div class="empty-element"></div>
      <article class="">
        <h2 class="pb-1">海況MAP <%= image_tag '/images/divesites/fukidashi03.png', class: "fukidashi01" %></h2>
          <div class="pb-2 transitions">
            <%= link_to '海況を投稿', new_condition_path, class: "goto-new" %>
            <%= link_to '本日の投稿一覧', conditions_path, class: "goto-index" %>
          </div>
        <div class="map-image">
          <div id='map'></div>
          <div class="d-flex justify-content-around pt-2 pin-discription">
            <%= image_tag '/images/conditions/open_pin.png', class: "sample-pin" %><span><small>:OPEN</small></span>
            <%= image_tag '/images/conditions/warning_pin.png', class: "sample-pin" %><span><small>:潜水注意</small></span>
            <%= image_tag '/images/conditions/close_pin.png', class: "sample-pin" %><span><small>:CLOSE</small></span>
            <%= image_tag '/images/conditions/no_info_pin.png', class: "sample-pin" %><span><small>:投稿なし</small></span>
          </div>
        </div>
        <div class="map-contents-wrap">
          <h5 class="pb-1"><span>選択した区域にある</span><span>ダイブサイト一覧</span></h5>
          <p><small></small></p>
          <div class="map-contents hidden">
            <%= render 'select_zone', zones: @zones %>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>
<script src="https://unpkg.com/@googlemaps/markerclustererplus/dist/index.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwZEHSacqV8SYTnZaKXGc7xFdyqZXkNwE&callback=initMap" async defer></script>

app/views/divesites/select_map.js.erb
// ajax
$(".map-contents").html("<%= j(render 'select_zone', zones: @zones) %>");

app/views/divesites/select_zone.js.erb
// ajax
$(".map-contents").html("<%= j(render 'select_zone', zones: @zones) %>");

app/views/divesites/show.html.erb
<div class="container-fluid">
  <div class="divesite-top">
    <%= image_tag('/images/divesites/divesite_image.jpg', class: "divesite-top-image") %>
    <div class="mask-gradation"></div>
    <div class="divesite-top-value">
      <h1 class="divesite-name" data-detail="<%= "#{@divesite.area} / #{@divesite.zone}" %>"></span><%= @divesite.name %>
      <span id="favorite-part"><%= render 'favorites/like', { favorite: @favorite, divesite: @divesite } %></span></h1>
    </div>
  </div>
  <div class="divesites-contents row">
    <div class="col-sm-0 col-md-1 col-lg-2"></div>
    <div class="col-sm-12 col-md-10 col-lg-8 ">
      <div class="wrapper">
        <a class="divesite-info-btn" href="#">
          <i class="fas fa-bars"> ダイブサイトinfo</i>
        </a>
        <div class="card-wrap">
          <% @conditions.each do |condition| %>
          <div class="card-item">
            <div class="d-flex justify-content-between">
              <h4><%= "#{condition.created_at.strftime("%Y年%m月%d日")}" %></h4>
              <p class="card-date"><small><%= "#{condition.created_at.strftime("%k:%M")}" %></small></p>
            </div>
            <div class="card-item-inner">
              <%= link_to "", condition_path(condition), class: "card-link" %>
              <div class="card-title">
                <% if condition.user.avatar? %>
                  <%= link_to image_tag(condition.user.avatar.thumb.url, class: "post-user-avatar"), user_path(condition.user.uid) %>
                <% else %>
                  <%= link_to image_tag('/images/thumb_default-avatar.png', class: "post-user-avatar"), user_path(condition.user.uid) %>
                <% end %>
                <strong class="pl-2"><%= link_to condition.user.name, user_path(condition.user.uid) %></strong>
                <span class="pl-4 status-icon"><%= image_tag(status_pin_helper(condition.status), width: '50px') %></span>
              </div>
              <div class="card-table">
                <table>
                  <tbody>
                    <tr>
                      <th>ポイント名<i class="fas fa-caret-right"></i></th>
                      <td><%= condition.divepoint %></td>
                    </tr>
                    <tr>
                      <th>海況<i class="fas fa-caret-right"></i></th>
                      <td><%= t("status.#{condition.status}") %></td>
                    </tr>
                    <tr>
                      <th>水温<i class="fas fa-caret-right"></i></th>
                      <td><%= condition.temperature %><span> ℃</span></td>
                    </tr>
                    <tr>
                      <th>透明度<i class="fas fa-caret-right"></i></th>
                      <td><%= condition.visibility %><span> m</span></td>
                    </tr>
                    <tr>
                      <th  class="card-comment">コメント<i class="fas fa-caret-down"></i></th>
                      <td></td>
                    </tr>
                    <tr>
                      <td colspan="2" class="card-comment02"><%= condition.content %></td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="card-content">
                <div class="card-image">
                  <% if condition.image? && condition.image.file.content_type.include?('image/') %>
                    <%= image_tag condition.image.thumb.url %>
                  <% elsif condition.image? && condition.image.file.content_type.include?('video/') %>
                    <%= video_tag condition.image, controls: true, controlsList: "nodownload", autobuffer: true, mute: true %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <div class="mb-2 d-flex justify-content-center">
          <%= paginate(@conditions) %>
        </div>
        <div class="pt-2 unobtrusive">
          <%= link_to conditions_path, class: "unobtrusive" do %>
            <%= "海況投稿一覧へ戻る" %><i class="fas fa-angle-right"></i>
          <% end %>
        </div>
        <div class="divesite-info">
          <a class="close-btn" href="#">
            <i class="fas fa-window-close"></i>
          </a>
          <span class="box-title">info</span>
          <table class="divesite-table">
            <tbody>
              <tr>
                <th>特徴</th>
                <td><%= @divesite.discription %></td>
              </tr>
              <tr>
                <th>所在地</th>
                <td><%= @divesite.address %></td>
              </tr>
              <tr>
                <th><span>☎︎</span><span class="call-ok"> (タップで電話可)</span></th>
                <td id="telephone"><%= link_to "#{@divesite.phone}", "tel:#{@divesite.phone.delete("-")}" %></td>
              </tr>
              <tr>
                <th>管理サービス</th>
                <td><%= @divesite.service %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-sm-0 col-md-1 col-lg-2"></div>
    </div>
  </div>
</div>