config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  root to: 'home#top'

  resources :users, only: %i[show] do
    member do
      get 'mypage', param: :uid
      get 'myprofile'
      get 'myfavorite'
      get 'mypost'
    end
  end
  resources :divesites, only: %i[index show] do
    collection do
      get 'select_map'
    end
  end
  resources :conditions, only: %i[index show new create destroy]
  resources :favorites, only: %i[create destroy]
  resources :relationships, only: %i[] do
    collection do
      post 'follow', to: 'relationships#create', as: :follow
    end
    member do
      delete 'unfollow', to: 'relationships#destroy', as: :unfollow
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prodive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://kit.fontawesome.com/27e4cb0d9e.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <div class="outermost">
      <header class="sticky-top">
        <div class="logo">
          <%= link_to image_tag("/images/LOGO.png", class: "logo"), root_path, class: 'pl-2' %>
        </div>
        <nav class="header-menu">
          <ul>
            <li>
              <%= link_to divesites_path, class: 'order-1 pr-2 bd-highlight' do %>
                <i class="fas fa-map-marked-alt"> 海況MAP</i>
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to conditions_path, class: 'order-2 pr-2 bd-highlight' do %>
                  <i class="fas fa-water"> 本日の海況</i>
                <% end %>
              </li>
              <li>
                <%= link_to new_condition_path, class: 'order-2 pr-2 bd-highlight' do %>
                  <i class="fas fa-plus"> 海況投稿</i>
                <% end %>
              </li>
              <li>
                <%= link_to mypage_user_path(current_user.uid), class: 'order-2 pr-2 bd-highlight' do %>
                  <i class="fas fa-portrait"> マイページ</i>
                <% end %>
              </li>
              <% if current_user.try(:admin?) %>
                <li>
                  <%= link_to rails_admin_path, class: 'order-3 pr-2 bd-highlight' do %>
                    <i class="fas fa-user-cog"> 管理者画面</i>
                  <% end %>
                </li>
              <% end %>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'order-3 pr-2 bd-highlight' do %>
                  <i class="fas fa-sign-out-alt"> ログアウト</i>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_session_path, class: 'pr-2 bd-highlight' do %>
                  <i class="fas fa-sign-in-alt"> ログイン</i>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: 'pr-2 bd-highlight' do %>
                  <i class="fas fa-user-plus">アカウント登録</i>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
        <div class="nav-toggle">
          <span></span>
          <span>Menu</span>
          <span></span>
        </div>
      </header>
      <main>
        <div class="flash_messages">
          <% flash.each do |key, value| %>
            <% key = 'info' if key == 'notice' %>
            <% key = 'secondary' if key == 'alert' %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
          <% end %>
        </div>
          <%= yield %>
          <%= javascript_include_tag 'common', 'home', 'divesites', 'map', 'conditions', 'users' %>
      </main>
      <% if controller.controller_name != 'home' %>
        <footer>
          <div class="footer-wrap">
            <%= image_tag("/images/footer-line.png", class: "footer-dividing-line") %>
            <p>© 2021 PRODIVE All rights reserved.</p>
          </div>
        </footer>
      <% end %>
    </div>
  </body>
</html>